[project]
name = "yolo-assignement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.6",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
    "ultralytics>=8.4.172",
]

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu132"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cuda" }
torchvision = { index = "pytorch-cuda" }

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "nbclient>=0.11.0",
]
